# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://wanshitaotao.github.io
date_format: "ordinal"
title: 码志
subtitle: "人生的路得自己走"
description: "黄涛涛的个人博客"
keywords: 码志, Huang Taotao, wanshitaotao, huangtaotao
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/wanshitaotao/wanshitaotao.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: Huang Taotao
organization: NUAA.
organization_url: https://www.nuaa.edu.cn
location: Nanjing, China
email: tao_nuaa@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: wanshitaotao
douban_username: wanshitaotao
facebook_username: wanshitaotao
weibo_username: wanshitaotao
zhihu_username: wanshitaotao
twitter_username: wanshitaotao

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: wanshitaotao
disqus_username: wanshitaotao

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
popular_repos: ['chinese-copywriting-guidelines','android-reverse-engineering', 'csdncommenter', 'mzlogin.github.io', 'vim-markdown-toc']
contribute_repos: ['sparanoid/chinese-copywriting-guidelines', 'waylife/RentCrawer']
